[2024-06-21T00:47:57.193+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T00:47:57.216+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemons.getpokemons manual__2024-06-21T00:47:55.410535+00:00 [queued]>
[2024-06-21T00:47:57.224+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemons.getpokemons manual__2024-06-21T00:47:55.410535+00:00 [queued]>
[2024-06-21T00:47:57.224+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-21T00:47:57.242+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): getpokemons> on 2024-06-21 00:47:55.410535+00:00
[2024-06-21T00:47:57.249+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=79) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-21T00:47:57.251+0000] {standard_task_runner.py:63} INFO - Started process 80 to run task
[2024-06-21T00:47:57.251+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemons', 'getpokemons', 'manual__2024-06-21T00:47:55.410535+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/python_operators.py', '--cfg-path', '/tmp/tmp1eosnbzr']
[2024-06-21T00:47:57.252+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask getpokemons
[2024-06-21T00:47:57.293+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemons.getpokemons manual__2024-06-21T00:47:55.410535+00:00 [running]> on host f9f27b1b4edb
[2024-06-21T00:47:57.379+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pokemons' AIRFLOW_CTX_TASK_ID='getpokemons' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T00:47:55.410535+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-21T00:47:55.410535+00:00'
[2024-06-21T00:47:57.380+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T00:47:57.380+0000] {logging_mixin.py:188} INFO - getting: https://pokeapi.co/api/v2/pokemon/?offset=0&limit=0
[2024-06-21T00:47:57.381+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T00:47:57.381+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/python_operators.py", line 25, in getpokemons
    output = output + requests.get(endpoint).json()['results']
                      ^^^^^^^^
NameError: name 'requests' is not defined
[2024-06-21T00:47:57.391+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pokemons, task_id=getpokemons, run_id=manual__2024-06-21T00:47:55.410535+00:00, execution_date=20240621T004755, start_date=20240621T004757, end_date=20240621T004757
[2024-06-21T00:47:57.404+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 50 for task getpokemons (name 'requests' is not defined; 80)
[2024-06-21T00:47:57.424+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-21T00:47:57.453+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-21T00:47:57.460+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
