[2024-06-23T01:51:09.936+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T01:51:09.965+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_example.clusterpokemonweights manual__2024-06-23T01:47:16.513377+00:00 [queued]>
[2024-06-23T01:51:09.977+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_example.clusterpokemonweights manual__2024-06-23T01:47:16.513377+00:00 [queued]>
[2024-06-23T01:51:09.977+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-23T01:51:09.998+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): clusterpokemonweights> on 2024-06-23 01:47:16.513377+00:00
[2024-06-23T01:51:10.009+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7782) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T01:51:10.010+0000] {standard_task_runner.py:63} INFO - Started process 7783 to run task
[2024-06-23T01:51:10.010+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemon_example', 'clusterpokemonweights', 'manual__2024-06-23T01:47:16.513377+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/python_operators.py', '--cfg-path', '/tmp/tmpqffgx7fb']
[2024-06-23T01:51:10.011+0000] {standard_task_runner.py:91} INFO - Job 101: Subtask clusterpokemonweights
[2024-06-23T01:51:10.055+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemon_example.clusterpokemonweights manual__2024-06-23T01:47:16.513377+00:00 [running]> on host c357804a93ab
[2024-06-23T01:51:10.173+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pokemon_example' AIRFLOW_CTX_TASK_ID='clusterpokemonweights' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T01:47:16.513377+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T01:47:16.513377+00:00'
[2024-06-23T01:51:10.175+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T01:51:10.176+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvn7pu9abq --system-site-packages --python=python
[2024-06-23T01:51:10.178+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T01:51:10.966+0000] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 228ms
[2024-06-23T01:51:10.966+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvn7pu9abq, clear=False, no_vcs_ignore=False, global=True)
[2024-06-23T01:51:10.967+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-06-23T01:51:10.967+0000] {process_utils.py:191} INFO -     added seed packages: pip==24.0
[2024-06-23T01:51:10.968+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-06-23T01:51:10.989+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvn7pu9abq/bin/pip install -r /tmp/venvn7pu9abq/requirements.txt
[2024-06-23T01:51:10.990+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T01:51:13.034+0000] {process_utils.py:191} INFO - Requirement already satisfied: numpy in /home/***/.local/lib/python3.12/site-packages (from -r /tmp/venvn7pu9abq/requirements.txt (line 1)) (1.26.4)
[2024-06-23T01:51:13.361+0000] {process_utils.py:191} INFO - Collecting scikit-learn (from -r /tmp/venvn7pu9abq/requirements.txt (line 2))
[2024-06-23T01:51:13.363+0000] {process_utils.py:191} INFO -   Using cached scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
[2024-06-23T01:51:13.662+0000] {process_utils.py:191} INFO - Collecting scipy>=1.6.0 (from scikit-learn->-r /tmp/venvn7pu9abq/requirements.txt (line 2))
[2024-06-23T01:51:13.664+0000] {process_utils.py:191} INFO -   Using cached scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-06-23T01:51:13.769+0000] {process_utils.py:191} INFO - Collecting joblib>=1.2.0 (from scikit-learn->-r /tmp/venvn7pu9abq/requirements.txt (line 2))
[2024-06-23T01:51:13.770+0000] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-06-23T01:51:13.825+0000] {process_utils.py:191} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn->-r /tmp/venvn7pu9abq/requirements.txt (line 2))
[2024-06-23T01:51:13.826+0000] {process_utils.py:191} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-06-23T01:51:13.867+0000] {process_utils.py:191} INFO - Using cached scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
[2024-06-23T01:51:13.894+0000] {process_utils.py:191} INFO - Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
[2024-06-23T01:51:13.897+0000] {process_utils.py:191} INFO - Using cached scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
[2024-06-23T01:51:13.970+0000] {process_utils.py:191} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-06-23T01:51:16.814+0000] {process_utils.py:191} INFO - Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
[2024-06-23T01:51:23.334+0000] {process_utils.py:191} INFO - Successfully installed joblib-1.4.2 scikit-learn-1.5.0 scipy-1.13.1 threadpoolctl-3.5.0
[2024-06-23T01:51:23.662+0000] {process_utils.py:191} INFO - 
[2024-06-23T01:51:23.663+0000] {process_utils.py:191} INFO - [notice] A new release of pip is available: 24.0 -> 24.1
[2024-06-23T01:51:23.663+0000] {process_utils.py:191} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-06-23T01:51:23.797+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvn7pu9abq/bin/python /tmp/venv-callgcvga9hl/script.py /tmp/venv-callgcvga9hl/script.in /tmp/venv-callgcvga9hl/script.out /tmp/venv-callgcvga9hl/string_args.txt /tmp/venv-callgcvga9hl/termination.log
[2024-06-23T01:51:23.798+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T01:51:26.672+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-06-23T01:51:26.673+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callgcvga9hl/script.py", line 103, in <module>
[2024-06-23T01:51:26.673+0000] {process_utils.py:191} INFO -     res = clusterpokemonweights(*arg_dict["args"], **arg_dict["kwargs"])
[2024-06-23T01:51:26.673+0000] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-23T01:51:26.674+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callgcvga9hl/script.py", line 67, in clusterpokemonweights
[2024-06-23T01:51:26.674+0000] {process_utils.py:191} INFO -     histogram = {i: labels.count(i) for i in set(centroids)}
[2024-06-23T01:51:26.674+0000] {process_utils.py:191} INFO -                     ^^^^^^
[2024-06-23T01:51:26.674+0000] {process_utils.py:191} INFO - NameError: name 'labels' is not defined
[2024-06-23T01:51:27.143+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T01:51:27.151+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'labels' is not defined
[2024-06-23T01:51:27.155+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pokemon_example, task_id=clusterpokemonweights, run_id=manual__2024-06-23T01:47:16.513377+00:00, execution_date=20240623T014716, start_date=20240623T015109, end_date=20240623T015127
[2024-06-23T01:51:27.177+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 101 for task clusterpokemonweights (Process returned non-zero exit status 1.
name 'labels' is not defined; 7783)
[2024-06-23T01:51:27.223+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T01:51:27.272+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T01:51:27.278+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
