[2024-06-23T00:13:20.771+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T00:13:20.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_example.metricspokemonweights manual__2024-06-23T00:05:08.961109+00:00 [queued]>
[2024-06-23T00:13:20.803+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_example.metricspokemonweights manual__2024-06-23T00:05:08.961109+00:00 [queued]>
[2024-06-23T00:13:20.804+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2024-06-23T00:13:20.818+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): metricspokemonweights> on 2024-06-23 00:05:08.961109+00:00
[2024-06-23T00:13:20.824+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5883) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T00:13:20.825+0000] {standard_task_runner.py:63} INFO - Started process 5884 to run task
[2024-06-23T00:13:20.826+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemon_example', 'metricspokemonweights', 'manual__2024-06-23T00:05:08.961109+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/python_operators.py', '--cfg-path', '/tmp/tmpa8ynbpvo']
[2024-06-23T00:13:20.827+0000] {standard_task_runner.py:91} INFO - Job 81: Subtask metricspokemonweights
[2024-06-23T00:13:20.868+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemon_example.metricspokemonweights manual__2024-06-23T00:05:08.961109+00:00 [running]> on host c357804a93ab
[2024-06-23T00:13:20.961+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pokemon_example' AIRFLOW_CTX_TASK_ID='metricspokemonweights' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:05:08.961109+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-23T00:05:08.961109+00:00'
[2024-06-23T00:13:20.962+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T00:13:20.963+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvf8iyrew0 --system-site-packages --python=python
[2024-06-23T00:13:20.964+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T00:13:21.724+0000] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 239ms
[2024-06-23T00:13:21.725+0000] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvf8iyrew0, clear=False, no_vcs_ignore=False, global=True)
[2024-06-23T00:13:21.725+0000] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-06-23T00:13:21.726+0000] {process_utils.py:191} INFO -     added seed packages: pip==24.0
[2024-06-23T00:13:21.726+0000] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-06-23T00:13:21.749+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvf8iyrew0/bin/pip install -r /tmp/venvf8iyrew0/requirements.txt
[2024-06-23T00:13:21.750+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T00:13:27.096+0000] {process_utils.py:191} INFO - 
[2024-06-23T00:13:27.097+0000] {process_utils.py:191} INFO - [notice] A new release of pip is available: 24.0 -> 24.1
[2024-06-23T00:13:27.097+0000] {process_utils.py:191} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-06-23T00:13:27.200+0000] {process_utils.py:183} INFO - Executing cmd: /tmp/venvf8iyrew0/bin/python /tmp/venv-callbej1_zkt/script.py /tmp/venv-callbej1_zkt/script.in /tmp/venv-callbej1_zkt/script.out /tmp/venv-callbej1_zkt/string_args.txt /tmp/venv-callbej1_zkt/termination.log
[2024-06-23T00:13:27.200+0000] {process_utils.py:187} INFO - Output:
[2024-06-23T00:13:29.423+0000] {process_utils.py:191} INFO - ----------------------------------------------------------------------------------------------------
[2024-06-23T00:13:29.424+0000] {process_utils.py:191} INFO - raw data:
[2024-06-23T00:13:29.424+0000] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-06-23T00:13:29.425+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callbej1_zkt/script.py", line 80, in <module>
[2024-06-23T00:13:29.425+0000] {process_utils.py:191} INFO -     res = metricspokemonweights(*arg_dict["args"], **arg_dict["kwargs"])
[2024-06-23T00:13:29.426+0000] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-23T00:13:29.426+0000] {process_utils.py:191} INFO -   File "/tmp/venv-callbej1_zkt/script.py", line 26, in metricspokemonweights
[2024-06-23T00:13:29.427+0000] {process_utils.py:191} INFO -     print(i,':',json.dumps(j, indent=4))
[2024-06-23T00:13:29.427+0000] {process_utils.py:191} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-23T00:13:29.428+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
[2024-06-23T00:13:29.428+0000] {process_utils.py:191} INFO -     **kw).encode(obj)
[2024-06-23T00:13:29.429+0000] {process_utils.py:191} INFO -           ^^^^^^^^^^^
[2024-06-23T00:13:29.429+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/encoder.py", line 202, in encode
[2024-06-23T00:13:29.429+0000] {process_utils.py:191} INFO -     chunks = list(chunks)
[2024-06-23T00:13:29.430+0000] {process_utils.py:191} INFO -              ^^^^^^^^^^^^
[2024-06-23T00:13:29.430+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/encoder.py", line 432, in _iterencode
[2024-06-23T00:13:29.431+0000] {process_utils.py:191} INFO -     yield from _iterencode_dict(o, _current_indent_level)
[2024-06-23T00:13:29.431+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/encoder.py", line 406, in _iterencode_dict
[2024-06-23T00:13:29.431+0000] {process_utils.py:191} INFO -     yield from chunks
[2024-06-23T00:13:29.432+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/encoder.py", line 439, in _iterencode
[2024-06-23T00:13:29.432+0000] {process_utils.py:191} INFO -     o = _default(o)
[2024-06-23T00:13:29.433+0000] {process_utils.py:191} INFO -         ^^^^^^^^^^^
[2024-06-23T00:13:29.433+0000] {process_utils.py:191} INFO -   File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
[2024-06-23T00:13:29.433+0000] {process_utils.py:191} INFO -     raise TypeError(f'Object of type {o.__class__.__name__} '
[2024-06-23T00:13:29.434+0000] {process_utils.py:191} INFO - TypeError: Object of type int32 is not JSON serializable
[2024-06-23T00:13:29.667+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T00:13:29.678+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
Object of type int32 is not JSON serializable
[2024-06-23T00:13:29.683+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=pokemon_example, task_id=metricspokemonweights, run_id=manual__2024-06-23T00:05:08.961109+00:00, execution_date=20240623T000508, start_date=20240623T001320, end_date=20240623T001329
[2024-06-23T00:13:29.705+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 81 for task metricspokemonweights (Process returned non-zero exit status 1.
Object of type int32 is not JSON serializable; 5884)
[2024-06-23T00:13:29.745+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T00:13:29.784+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T00:13:29.790+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
